user  nginx;
worker_processes  1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name working-shop.chickenkiller.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            allow all;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
